theme: minima
title: Dan Mills
email: mills.dan@proton.me

# basic options
author: Dan Mills
description: Personal website of Dan Mills

# Build settings
markdown: kramdown

linkedin_username: dan-mills
