#theme: jekyll-theme-minimal
theme: jekyll-theme-minima
title: Daniel James Mills
email: daniel.mills@quantinuum.com

# basic options
author: Daniel Mills
description: Personal website of Daniel Mills

# Build settings
markdown: kramdown

#github_username: danmills0
linkedin_username: dan-mills
# facebook_username: daniel.mills.7965
#twitter_username: danmills0
