# theme: jekyll-theme-minimal
theme: minima
title: Dan Mills
email: daniel.mills@quantinuum.com

# basic options
author: Dan Mills
description: Personal website of Dan Mills

# Build settings
markdown: kramdown

#github_username: danmills0
linkedin_username: dan-mills
# facebook_username: daniel.mills.7965
#twitter_username: danmills0
